Cyfrin/solidity-by-example.github.io

src/pages/0.5/events/__snapshots__/index.test.tsx.snap, src/pages/0.5/events/index.html.ts, src/pages/0.5/events/index.md, src/pages/0.6/events/__snapshots__/index.test.tsx.snap, src/pages/0.6/events/index.html.ts, src/pages/0.6/events/index.md
Spelling error found in the wild at https://solidity-by-example.org/0.6/events/
=> Replace "cass" with "cases" everywhere

src/pages/call/Call.sol
The fallback function should be "fallback() external payable" instead of "receive() external payable" in solidity 0.7.6.
=> Fallback function name

src/pages/primitives/Primitives.sol
Just a minor change. 
Shouldn't this say: Like uint, different ranges are available from int8 to int256 (instead of uint).
=> Update comment for int's

src/pages/hello-world/HelloWorld.sol
I noticed a typo in the comment regarding the function of the caret in the pragma versioning. I believe the comment should read `and less than 0.9.0` rather than `and less than 0.8.0`.
=> docs(pragma): fixed comment regarding pragma semver

src/pages/app/english-auction/EnglishAuction.sol
Use `safeTransferFrom` instead.  see #194
=> ERC721 does not specify a `transfer` function.

src/pages/function/Function.sol
[The neither/nor combination expresses negation all by itself](https://english.stackexchange.com/a/30077/79962), so it shouldn't be used in combination with another negative, i.e. 'cannot'.
=> Fix typo and grammar

src/pages/app/bi-directional-payment-channel/BiDirectionalPaymentChannel.sol, src/pages/app/bi-directional-payment-channel/index.html.ts, src/pages/app/uni-directional-payment-channel/UniDirectionalPaymentChannel.sol, src/pages/app/uni-directional-payment-channel/index.html.ts, src/pages/hacks/signature-replay/PreventSigReplay.sol, src/pages/hacks/signature-replay/SigReplay.sol, src/pages/hacks/signature-replay/index.html.ts, src/pages/import/index.html.ts, src/pages/import/index.md
Hi!
I updated some contracts to `release-4.5` because I wasn't able to compile `release-3.3` due solidity version was limited as `>=0.6.0 <0.8.0`.
Also there is two small fixes: 
- Rule 4 at [english-auction](https://solidity-by-example.org/app/english-auction/) to disallow withdraw to the highestBidder.
- Convert sender address as payable at [uni-directional-payment-channel](https://solidity-by-example.org/app/uni-directional-payment-channel/).
Thanks!
=> Update contract lib version

src/pages/app/create2/Create2.sol
It is cleaner and also more gas efficient to invoke create2 this way.
Some context: https://twitter.com/rage_pit/status/1495083730754543616
=> Use newer create2 syntax

src/pages/structs/Structs.sol
In the examples I updated, the argument has the storage location memory.
When the functions get called externally, the arguments are kept in calldata
and copied to memory during ABI decoding (using the opcode calldataload and mstore).
When the argument is read in the function, the value is accesses in memory
using a mload. We can avoid all this logic by simply using calldata for
read-only arguments. In my proposal, instead of going via memory,
the value is directly read from calldata using calldataload.
I think this is important to expose good practices like this one to the user.
----
What do you think about this @t4sk? I'm ready to open a PR that changes memory argument to calldata argument when needed.
=> improvement: using calldata instead of memory

src/pages/app/erc721/ERC721.sol
Now requires caller to be owner to be able to burn token.
=> Updated burn function in erc721

src/pages/app/upgradeable-proxy/UpgradeableProxy.sol
Call to encode for function getProxyAdmin is Proxy.admin; and, getProxyImplementation is Proxy.implementation
=> correction in call to encode

src/pages/primitives/index.html.ts
Primitives may benefit from explicitly declaring `uint256` and `int256` before `uint` and `int`.
=> explicitly declare uint256

src/pages/hacks/front-running/PreventFrontRunning.sol
This PR resolves two bugs in the PreventFrontrunning.sol.
1. The attacker can attack this smart contract by submitting both `commitSolution()` and `revealSolution()` transactions in the same block after seeing the correct solution in the mempool.
**Solution:** The commit 48a0b38ad2217a61ae41f1ecc80dff414cd4506c resolves this by ensuring the commit is done before the current block.
2. The solution-checking logic is incorrect since the correct solution must have the same hash as stored in the smart contract, not different. (Credits to @jokopopo for this issue)
**Solution:** The commit 63a2e19628750cb4598f9e2a02e67bf1e93d818e resolves this by changing the comparison operator from `!=` to `==`.
=> Fixes for PreventFrontrunning.sol

src/pages/call/index.md, src/pages/enum/index.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "recommend" to "recommended".
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

src/pages/defi/vault/index.md, src/pages/hashing/index.md
This pull request addresses grammatical issues and article usage improvements in the documentation:
1. In `index.md` (Vault), changed "an user" to "a user" for proper article usage.
2. In `index.md` (Hashing), corrected "a input" to "an input" for proper article usage.
These changes enhance clarity and correctness in the documentation.
=> Fix Grammar and Article Usage in Vault and Hashing Documentation

README.md, src/pages/call/index.md, src/pages/defi/vault/index.md, src/pages/hashing/index.md
**src/pages/hashing/index.md**
- `Mics ` → `Misc `
**README.md**
- `recommend ` → `recommended `
**src/pages/defi/vault/index.md**
- `an user` → `a user `
- `burn ` → `burns `
**src/pages/hashing/index.md**
- `a input ` → `an input `
=> Fix errors in documentation files

contracts/src/hacks/self-destruct/PreventForceEther.sol, src/pages/hacks/self-destruct/PreventForceEther.sol
In the Self Destruct Preventative Techniques section, the `claimReward` function contains a logical error where it sets `balance = 0` before attempting to transfer funds. This causes the transfer to fail since it tries to send 0 ETH instead of the actual contract balance.
Current code:
```solidity
function claimReward() public {
require(msg.sender == winner, "Not winner");
balance = 0;  // <-- Problem: Sets balance to 0 before transfer
(bool sent,) = msg.sender.call{value: balance}("");  // Will always try to send 0 ETH
require(sent, "Failed to send Ether");
}
```
Proposed fix:
```solidity
function claimReward() public {
require(msg.sender == winner, "Not winner");
uint256 amount = balance;
balance = 0;
(bool sent,) = msg.sender.call{value: amount}("");
require(sent, "Failed to send …
```
=> Fix: Remove incorrect balance reset in claimReward function inside Self Destruct Forced Prevention Contract

src/pages/call/index.md, src/pages/hashing/index.md
Changes Made
1. In src/pages/call/index.md:
- However it is not the recommend way to call existing functions.
+ However it is not the recommended way to call existing functions.
Reason: The word "recommend" should be "recommended" as it's being used as an adjective in this context. The "-ed" suffix is required for the past participle form.
2. In src/pages/hashing/index.md:
- Creating a deterministic unique ID from a input
+ Creating a deterministic unique ID from an input
Reason: The article "a" should be "an" when it precedes a word that begins with a vowel sound. Since "input" begins with a vowel sound, "an" is the correct article to use.
Summary
These changes improve the grammatical accuracy of the documentation, making it more professional and easier to read. The corrections follow …
=> improve the grammatical accuracy of the documentation

src/pages/app/multi-sig-wallet/index.md, src/pages/hacks/denial-of-service/index.html.ts, src/pages/hacks/denial-of-service/index.md, src/pages/hacks/re-entrancy/index.html.ts, src/pages/hacks/re-entrancy/index.md
This PR fixes typographical errors and incorrect usage of articles ("a" vs "an") in documentation and code comments to improve clarity and grammatical accuracy.
--
 
- Corrected article usage based on whether the following word starts with a consonant or vowel sound.
- Fixed minor typographical errors for consistency and readability.
 
 
---
 
These changes are focused solely on improving documentation and code comments without affecting logic or functionality.
=> Fix typographical errors and incorrect usage of articles

src/pages/fallback/index.md
* Added a flowchart to the `src/pages/fallback/index.md` file to help understand the conditions under which Solidity calls the `receive` or `fallback` function.
The flowchart breaks it down step by step:
It shows that if Ether is sent without data, Solidity checks if a receive function exists and calls it.
If Ether is sent with data, or if the receive function doesn’t exist, the fallback function is called.
By adding this diagram, it’s easier for beginners to understand how Solidity handles incoming Ether, especially when the explanation in text might feel too abstract. The flowchart is placed right after the explanation of receive to provide a visual aid before jumping into the code examples.
This contribution makes the documentation more beginner-friendly and accessible.
=> Added flowchart to explain fallback and receive function logic

contracts/src/app/erc1155/ERC1155.sol
This PR updates the `supportsInterface` function in the contract to use the `pure` mutability specifier instead of `view`. The change reflects the actual behavior of the function, aligns with Solidity's best practices, and addresses a compiler warning without altering the functionality or breaking EIP-165 compliance.
---
In the [EIP-165 example implementation](https://eips.ethereum.org/EIPS/eip-165), the `supportsInterface` function is marked as `view` because it reads from a `mapping`:
```solidity
mapping(bytes4 => bool) internal supportedInterfaces;
function supportsInterface(bytes4 interfaceID) external view returns (bool) {
return supportedInterfaces[interfaceID];
}
```
Here, the view mutability is required since the function accesses blockchain storage (supportedInterfaces). However, …
=> Update `supportsInterface` Mutability to `pure`

contracts/src/delegatecall/Delegatecall.sol
This PR adds a new function `setVarsCall` in contract A to demonstrate the difference between `delegatecall` and `call`
=> Add comparison between call and delegatecall in contract A

src/pages/events/Events.sol, src/pages/gas/Gas.sol
1. In src/pages/gas/Gas.sol:
Old: // Gas spent are not refunded.
New: // Gas spent is not refunded.
Reason: "Gas spent" is treated as a singular noun phrase requiring singular verb "is"
2. In src/pages/events/Events.sol:
Old: // Indexed parameters helps you filter the logs
New: // Indexed parameters help you filter the logs
Reason: "Parameters" is plural requiring plural verb "help"
=> Fix Grammar Issues in Comments

contracts/src/hacks/front-running/PreventFrontRunning.sol, src/pages/hacks/front-running/PreventFrontRunning.sol
This PR fixes typos in the `PreventFrontRunning.sol` file and its associated documentation. Specifically:
1. Corrected "an password" to "a password."
2. Improved wording consistency in the explanation of `keccak256` hash generation.
These changes enhance the readability and professionalism of the contract's inline documentation and related content.
---
- Corrected grammatical typos in **contracts/src/hacks/front-running/PreventFrontRunning.sol**.
- Updated corresponding text in **src/pages/hacks/front-running/PreventFrontRunning.sol**.
---
I have:
=> Fix: Typos in documentation

contracts/src/import/Import.sol, src/pages/import/Import.sol
The word "it's" is a contraction meaning "it is" or "it has", while "its" is the possessive form of "it". In this context, we are referring to the possessive form - the name belonging to Foo.sol, so "its" is the correct usage.
This change improves code documentation clarity and maintains proper English grammar in comments.
=>  documentation clarity 

src/pages/app/crowd-fund/index.md, src/pages/app/erc721/index.md
Fixed spelling errors in the `index.md` files:
- Changed "crowd fund" to "crowdfunding"
- Corrected "non fungible" to "non-fungible"
- Fixed "it's" to "its" in the context of the campaign goal
=> Fix spelling

src/pages/hashing/index.md
I encountered a gap in my memory and, while searching for an example, I opened the page expecting to find an encode example or at least an explanation. Since it was missing, I added a section that would have helped me and could benefit others in a similar situation.
=> Adding abi.encode and abi.encodePacked differences

src/pages/array/index.md, src/pages/gas-golf/GasGolf.sol, src/pages/gas/index.html.ts
Documentation Text:
Old:
Array can have a compile-time fixed size or a dynamic size.
New:
An array can have a compile-time fixed size or a dynamic size.
Reason:
Added the article "An" for correct grammar when referring to a singular, countable noun.
Solidity Code Comment (Gas Contract):
Old:
// uncheck i overflow/underflow - 47309 gas
New:
// unchecked i overflow/underflow - 47309 gas
Reason:
Corrected "uncheck" to "unchecked" to properly describe the unchecked arithmetic operation in Solidity.
HTML Code Comment:
Old:
<span class="hljs-comment">// Here we run a loop until all of the gas are spent</span>
New:
<span class="hljs-comment">// Here we run a loop until all of the gas is spent</span>
Reason:
Changed "are spent" to "is spent" because "gas" is an uncountable noun, and the singular …
=> Grammar and Clarity Fixes

src/pages/defi/constant-sum-amm/CSAMM.sol, src/pages/defi/staking-rewards/index.html.ts, src/pages/ether-units/index.md, src/pages/evm/memory/YulMem.sol, src/pages/evm/memory/index.md, src/pages/function-selector/index.md
have same > have the same
__blank > _blank
100 cent > 100 cents
store > stored
Solidity document > Solidity documentation
Take for example, > Take, for example,
=> documentation clarity

src/pages/app/multi-sig-wallet/index.md, src/pages/app/time-lock/TimeLock.sol
Corrected subject-verb agreement ("has" → "have") to match the plural subject "owners."
Improved grammar and clarity by adding a hyphen to "ABI-encoded" and fixing "data send" → "data to send."
=> Fix grammatical errors in documentation and comments

contracts/src/evm/storage/EVMStorage.sol, src/pages/evm/storage/EVMStorage.sol, src/pages/evm/storage/index.html.ts
Updates incorrect spelling of "keccak256" in comments within the EVMStorage contract.
Changes:
- Fixed typo "keccack256" to "keccak256" in mapping storage slot comments
- Updated both EVMStorageMapping and EVMStorageNestedMapping contracts
- Maintains consistent spelling throughout the codebase
This is a documentation-only change that improves code readability and consistency.
=> Fix keccak256 typo in EVMStorage contract comments

src/pages/abi-encode/AbiEncode.sol, src/pages/abi-encode/index.html.ts, src/pages/app/erc20/index.html.ts
✅ **AbiEncode.sol**
- Clarified inline comments explaining the behavior of `abi.encodeWithSignature` and `abi.encodeWithSelector`.
- Replaced misleading comments about typo checking to avoid confusion.
✅ **index.html.ts (abi-encode)**
- Updated HTML comments to better explain how ABI encoding works and the lack of compile-time checks.
✅ **index.html.ts (erc20)**
- Refactored metadata:
- Updated the `title` for better context.
- Enhanced the `description`.
- Expanded `keywords` to improve discoverability (added "mint", "burn", "token swap", "dapp").
=> Improve ABI encoding comments and refactor ERC20 Metadata

contracts/src/inheritance/Inheritance.sol, src/pages/inheritance/Inheritance.sol, src/pages/inheritance/index.html.ts, src/pages/inheritance/index.md
Some editors could have trouble accurately rendering these characters, with these characters showing up as gibberish or causing formatting problems. It will confuse readers.
=> Fix: quotation mark

contracts/src/defi/chronicle-price-oracle/chroniclePriceOracle.sol, src/keywords.json, src/nav.ts, src/pages/defi/chronicle-price-oracle/chroniclePriceOracle.sol, src/pages/defi/chronicle-price-oracle/index.html.ts, src/pages/defi/chronicle-price-oracle/index.md, src/pages/defi/chronicle-price-oracle/index.tsx, src/pages/signature/index.md, src/routes.tsx, src/search.json
Add section under DeFi on using a Chronicle Oracle for getting a price
=> Add Chronicle example
