- src/pages/constructor/index.html.ts
Example references E as the last  contract constructor executed, where as the contract is named F.
> Fix contract name

- src/pages/gas/index.md
> Fix typo in gas example

- src/pages/structs/Structs.sol
> Update Structs.sol - Fix Typo

- src/pages/primitives/Primitives.sol
Adding public tag to the variables. Beginners may not know why they weren't showing up. This is my first pull request in github. If I'm doing it wrong please let me know!
> Adding 'public'

- src/pages/hacks/overflow/Overflow.sol
Hi, buddy, the calculation of `_secondsToIncrease` missing adding one to reach the condition to the overflow. 
The test for the codes has been done on remix.
> The calculation of _secondsToIncrease

- src/pages/app/uni-directional-payment-channel/UniDirectionalPaymentChannel.sol
- src/pages/constructor/Constructor.sol
- src/pages/error/Error.sol
- src/pages/ether-units/EtherUnits.sol
- src/pages/primitives/Primitives.sol
These are some minor changes that I made while learning.
> Minor fixes

- src/pages/new-contract/NewContract.sol
Adding the new car contract address into the 'car' array makes it easier to see the new contracts being created. This helped me visually see the result of the code.
> Add new contract address to car contract factory

- src/pages/primitives/Primitives.sol
Add '256' to uint and int to better reflect comments
> Add '256' to uint and int

- src/pages/hacks/hiding-malicious-code-with-external-contract/ExternalContract.sol
> fix hiding-malicious-code-with-external-contract

- src/pages/primitives/Primitives.sol
Source: 
- https://docs.soliditylang.org/en/v0.5.10/types.html#bytes-and-strings-as-arrays
- https://jeancvllr.medium.com/solidity-tutorial-all-about-bytes-9d88fdb22676
> added byte type

- src/pages/array/ArrayReplaceFromEnd.sol
Fix issue #197 
Assert statements incorrectly used = instead of ==.
> Replace = with == to fix #197

- src/pages/app/erc20/TokenSwap.sol
fix typo. 'Appprove' => 'Approve'
> Update TokenSwap.sol fix typo of approve

- src/pages/delegatecall/index.html.ts
- src/pages/delegatecall/index.md
correction of "executed" spelling
> Correcting just a little typo

- src/pages/if-else/IfElse.sol
Mention the fact the "?" operator is called the ternary operator.
That will probably help new people to search what this operator is in the documentation.
> doc(if/else): add ternary clarification

- src/pages/gas-golf/GasGolf.sol
Remove the unnecessary Internal Call and Save the Some Gas.
> Increase the Gas Saving

- src/pages/call/Call.sol
- src/pages/call/index.html.ts
Got a bit confused with 'A' and 'B', so thought this would help. Let me know if there's anything more to change, thanks.
> Suggestion for 'Call'

- src/pages/app/bi-directional-payment-channel/BiDirectionalPaymentChannel.sol
- src/pages/hacks/signature-replay/PreventSigReplay.sol
- src/pages/hacks/signature-replay/SigReplay.sol
https://docs.soliditylang.org/en/v0.8.17/080-breaking-changes.html?highlight=abiencoder#solidity-v0-8-0-breaking-changes
> removed safeMath and AbiEncoderV2

- src/pages/library/Library.sol
> I think I found a typo

- src/pages/call/Call.sol
1. Made function and address payable
2. Fix call params, without params it call fallback of self.
> Fix fallback function call from abi

- src/pages/hacks/accessing-private-data/Vault.sol
Fix the mismatch of contract address in the comments.
> Correct contract address in the comments

- src/pages/app/iterable-mapping/IterableMapping.sol
> IterableMapping.sol gas optimization

- src/pages/tests/echidna/EchidnaTestTimeAndCaller.sol
- src/pages/tests/echidna/TestEchidna.sol
- src/pages/tests/echidna/index.md
Hello,
In this PR are the changes to the echidna examples as suggested in this [issue](https://github.com/solidity-by-example/solidity-by-example.github.io/issues/264).
Cheers.
> update echidna tests

- src/nav.ts
- src/pages/events-advanced/EventsAdvanced.sol
- src/pages/events-advanced/index.html.ts
- src/pages/events-advanced/index.md
- src/pages/events-advanced/index.tsx
- src/routes.tsx
This pull request introduces advanced examples of Solidity events. It builds on the basics covered in the existing Events documentation with two examples: `EventDrivenArchitecture` and `EventSubscription`. These examples demonstrate event-driven architecture and real-time event subscription mechanisms.
- **Added `EventDrivenArchitecture` Contract**:
- Demonstrates the use of events to coordinate and trigger different stages of a process (e.g., initiating and confirming transfers).
- Includes two events: `TransferInitiated` and `TransferConfirmed`.
- Implements functions to initiate and confirm transfers.
- **Added `EventSubscription` Contract**:
- Showcases how to implement event subscriptions for real-time updates.
- Includes the `subscribe` and `unsubscribe` functions to manage …
> Add "Events Advanced" page and route

- contracts/src/hacks/front-running/PreventFrontRunning.sol
Hello
I found several spelling issues in your docs.
Br, Elias.
> docs fix PreventFrontRunning.sol

- src/pages/call/index.md
- src/pages/enum/index.md
- src/pages/hashing/index.md
> fix errors in documentation files 

- contracts/src/delegatecall/Delegatecall.sol
- src/pages/app/erc1155/ERC1155.sol
This PR enhances the tutorial by adding an event to log the outcome of a `delegatecall`, showcasing real-world best practices in smart contract development.
---
1. **Debugging**: Logs the success or failure of `delegatecall` to help learners understand and troubleshoot contract behavior.
2. **Educational Value**: Demonstrates how to implement transparency and observability in smart contracts.
3. **Real-World Relevance**: Shows learners how to track critical operations, aligning with common production practices.
---
```solidity
function setVars(address _contract, uint256 _num) public payable {
// A's storage is set, B is not modified.
(bool success, bytes memory data) = _contract.delegatecall(
abi.encodeWithSignature("setVars(uint256)", _num)
);
}
```
```solidity
event …
```
> Adding Event After `delegatecall`

- contracts/src/app/bi-directional-payment-channel/BiDirectionalPaymentChannel.sol
- contracts/src/defi/stable-swap-amm/StableSwap.sol
- contracts/src/evm/storage/EVMStorage.sol
- contracts/src/hacks/honeypot/HoneyPot.sol
**agains - against**
**Reccalcuate - Recalculate**
**EVMStoratePackedSlotBytes - EVMStoragePackedSlotBytes**
**reentracy - reentrancy**
> Fix Grammar Issues in Comments

- contracts/src/app/time-lock/TimeLock.sol
_____________________________________________
Hey !
I fixed several spelling issues.Glad I could help .
Br, Guayaba221.
> typo Update TimeLock.sol

- src/pages/signature/index.md
We're used to use the console in the web browser or directly a javascript code just like in the example linked in the page, but since there isn't a Remix usage and I was searching how to it, here it is!
It is using the first and second accounts.
> Explanation on the `signature` example

- contracts/src/hacks/hiding-malicious-code-with-external-contract/ExternalContract.sol
- contracts/src/hacks/re-entrancy/ReEntrancy.sol
- contracts/src/hacks/signature-replay/ECDSA.sol
- contracts/src/inheritance/Inheritance.sol
- contracts/src/signature/Signature.sol
- src/pages/app/bi-directional-payment-channel/BiDirectionalPaymentChannel.sol
- src/pages/app/erc20/TokenSwap.sol
description in the tittle 
thanks !
> chore: fixed all the minor typos

- src/pages/hacks/denial-of-service/DenialOfService.sol
- src/pages/hacks/hiding-malicious-code-with-external-contract/index.md
- src/pages/hacks/phishing-with-tx-origin/index.md
- src/pages/hacks/randomness/index.html.ts
- src/pages/hacks/self-destruct/ForceEther.sol
- src/pages/hacks/signature-replay/index.md
src/pages/hacks/denial-of-service/DenialOfService.sol
challenge - challenges
src/pages/hacks/hiding-malicious-code-with-external-contract/index.md
In Solidity - In Solidity, 
src/pages/hacks/phishing-with-tx-origin/index.md
Preventative - Preventive
src/pages/hacks/randomness/index.html.ts
it is win - it is to win
src/pages/hacks/self-destruct/ForceEther.sol
decides - decide
src/pages/hacks/signature-replay/index.md
reduce number - reduce the number
> fix error and correction

- src/index.css
- src/pages/index.tsx
- src/pages/interface/index.html.ts
- src/pages/library/index.md
- src/pages/primitives/index.html.ts
- src/pages/visibility/index.md
src/index.css
body.dak - body.dark 4х
body.dary - body.dark 3х
src/pages/index.tsx
code are explained - code is explained
src/pages/interface/index.html.ts
of interface - of an interface
src/pages/library/index.md
variable - variables
src/pages/primitives/index.html.ts
represent - represents
src/pages/visibility/index.md
inside contract - inside a contract
> correction comments and functions

- src/pages/hacks/overflow/index.html.ts
- src/pages/hacks/overflow/index.md
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/math/SafeMath.sol - broken link
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.3/contracts/utils/math/SafeMath.sol -work link
> fix openzeppelin links 
